pipeline:
  enabled: true
  script: "integration-tests"
job:
  dockerfile: "docker/images/integration-tests/Dockerfile"
  selenium: "3.5.3"
  selenium_nodes: 5
  base_url: 'https://developer.allizom.org'
  tests: "not login"
